/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VetoRouteImport } from './routes/veto'
import { Route as PairingRouteImport } from './routes/pairing'
import { Route as MatchupRouteImport } from './routes/matchup'
import { Route as MapOrderRouteImport } from './routes/map-order'
import { Route as IndexRouteImport } from './routes/index'

const VetoRoute = VetoRouteImport.update({
  id: '/veto',
  path: '/veto',
  getParentRoute: () => rootRouteImport,
} as any)
const PairingRoute = PairingRouteImport.update({
  id: '/pairing',
  path: '/pairing',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchupRoute = MatchupRouteImport.update({
  id: '/matchup',
  path: '/matchup',
  getParentRoute: () => rootRouteImport,
} as any)
const MapOrderRoute = MapOrderRouteImport.update({
  id: '/map-order',
  path: '/map-order',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/map-order': typeof MapOrderRoute
  '/matchup': typeof MatchupRoute
  '/pairing': typeof PairingRoute
  '/veto': typeof VetoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/map-order': typeof MapOrderRoute
  '/matchup': typeof MatchupRoute
  '/pairing': typeof PairingRoute
  '/veto': typeof VetoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/map-order': typeof MapOrderRoute
  '/matchup': typeof MatchupRoute
  '/pairing': typeof PairingRoute
  '/veto': typeof VetoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/map-order' | '/matchup' | '/pairing' | '/veto'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/map-order' | '/matchup' | '/pairing' | '/veto'
  id: '__root__' | '/' | '/map-order' | '/matchup' | '/pairing' | '/veto'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MapOrderRoute: typeof MapOrderRoute
  MatchupRoute: typeof MatchupRoute
  PairingRoute: typeof PairingRoute
  VetoRoute: typeof VetoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/veto': {
      id: '/veto'
      path: '/veto'
      fullPath: '/veto'
      preLoaderRoute: typeof VetoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pairing': {
      id: '/pairing'
      path: '/pairing'
      fullPath: '/pairing'
      preLoaderRoute: typeof PairingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matchup': {
      id: '/matchup'
      path: '/matchup'
      fullPath: '/matchup'
      preLoaderRoute: typeof MatchupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map-order': {
      id: '/map-order'
      path: '/map-order'
      fullPath: '/map-order'
      preLoaderRoute: typeof MapOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MapOrderRoute: MapOrderRoute,
  MatchupRoute: MatchupRoute,
  PairingRoute: PairingRoute,
  VetoRoute: VetoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
