/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VetoRouteImport } from './routes/veto'
import { Route as PairingRouteImport } from './routes/pairing'
import { Route as MatchupRouteImport } from './routes/matchup'
import { Route as MapOrderRouteImport } from './routes/map-order'
import { Route as HealthRouteImport } from './routes/health'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamedayIdRouteImport } from './routes/gameday.$id'
import { Route as ApiSplatRouteImport } from './routes/api/$'

const VetoRoute = VetoRouteImport.update({
  id: '/veto',
  path: '/veto',
  getParentRoute: () => rootRouteImport,
} as any)
const PairingRoute = PairingRouteImport.update({
  id: '/pairing',
  path: '/pairing',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchupRoute = MatchupRouteImport.update({
  id: '/matchup',
  path: '/matchup',
  getParentRoute: () => rootRouteImport,
} as any)
const MapOrderRoute = MapOrderRouteImport.update({
  id: '/map-order',
  path: '/map-order',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamedayIdRoute = GamedayIdRouteImport.update({
  id: '/gameday/$id',
  path: '/gameday/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/map-order': typeof MapOrderRoute
  '/matchup': typeof MatchupRoute
  '/pairing': typeof PairingRoute
  '/veto': typeof VetoRoute
  '/api/$': typeof ApiSplatRoute
  '/gameday/$id': typeof GamedayIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/map-order': typeof MapOrderRoute
  '/matchup': typeof MatchupRoute
  '/pairing': typeof PairingRoute
  '/veto': typeof VetoRoute
  '/api/$': typeof ApiSplatRoute
  '/gameday/$id': typeof GamedayIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/health': typeof HealthRoute
  '/map-order': typeof MapOrderRoute
  '/matchup': typeof MatchupRoute
  '/pairing': typeof PairingRoute
  '/veto': typeof VetoRoute
  '/api/$': typeof ApiSplatRoute
  '/gameday/$id': typeof GamedayIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/health'
    | '/map-order'
    | '/matchup'
    | '/pairing'
    | '/veto'
    | '/api/$'
    | '/gameday/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/health'
    | '/map-order'
    | '/matchup'
    | '/pairing'
    | '/veto'
    | '/api/$'
    | '/gameday/$id'
  id:
    | '__root__'
    | '/'
    | '/health'
    | '/map-order'
    | '/matchup'
    | '/pairing'
    | '/veto'
    | '/api/$'
    | '/gameday/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HealthRoute: typeof HealthRoute
  MapOrderRoute: typeof MapOrderRoute
  MatchupRoute: typeof MatchupRoute
  PairingRoute: typeof PairingRoute
  VetoRoute: typeof VetoRoute
  ApiSplatRoute: typeof ApiSplatRoute
  GamedayIdRoute: typeof GamedayIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/veto': {
      id: '/veto'
      path: '/veto'
      fullPath: '/veto'
      preLoaderRoute: typeof VetoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pairing': {
      id: '/pairing'
      path: '/pairing'
      fullPath: '/pairing'
      preLoaderRoute: typeof PairingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matchup': {
      id: '/matchup'
      path: '/matchup'
      fullPath: '/matchup'
      preLoaderRoute: typeof MatchupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map-order': {
      id: '/map-order'
      path: '/map-order'
      fullPath: '/map-order'
      preLoaderRoute: typeof MapOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gameday/$id': {
      id: '/gameday/$id'
      path: '/gameday/$id'
      fullPath: '/gameday/$id'
      preLoaderRoute: typeof GamedayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HealthRoute: HealthRoute,
  MapOrderRoute: MapOrderRoute,
  MatchupRoute: MatchupRoute,
  PairingRoute: PairingRoute,
  VetoRoute: VetoRoute,
  ApiSplatRoute: ApiSplatRoute,
  GamedayIdRoute: GamedayIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
