/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VetoRouteImport } from './routes/veto'
import { Route as PairingRouteImport } from './routes/pairing'
import { Route as MatchupRouteImport } from './routes/matchup'
import { Route as MapOrderRouteImport } from './routes/map-order'
import { Route as HealthRouteImport } from './routes/health'
import { Route as UnauthenticatedRouteImport } from './routes/_unauthenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RefactorIndexRouteImport } from './routes/refactor/index'
import { Route as UnauthenticatedGamedayIdRouteImport } from './routes/_unauthenticated/gameday.$id'
import { Route as ApiSplatRouteImport } from './routes/api/$'

const VetoRoute = VetoRouteImport.update({
  id: '/veto',
  path: '/veto',
  getParentRoute: () => rootRouteImport,
} as any)
const PairingRoute = PairingRouteImport.update({
  id: '/pairing',
  path: '/pairing',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchupRoute = MatchupRouteImport.update({
  id: '/matchup',
  path: '/matchup',
  getParentRoute: () => rootRouteImport,
} as any)
const MapOrderRoute = MapOrderRouteImport.update({
  id: '/map-order',
  path: '/map-order',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthenticatedRoute = UnauthenticatedRouteImport.update({
  id: '/_unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RefactorIndexRoute = RefactorIndexRouteImport.update({
  id: '/refactor/',
  path: '/refactor/',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthenticatedGamedayIdRoute = UnauthenticatedGamedayIdRouteImport.update(
  {
    id: '/gameday/$id',
    path: '/gameday/$id',
    getParentRoute: () => UnauthenticatedRoute,
  } as any,
)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof UnauthenticatedRouteWithChildren
  '/health': typeof HealthRoute
  '/map-order': typeof MapOrderRoute
  '/matchup': typeof MatchupRoute
  '/pairing': typeof PairingRoute
  '/veto': typeof VetoRoute
  '/api/$': typeof ApiSplatRoute
  '/gameday/$id': typeof UnauthenticatedGamedayIdRoute
  '/refactor/': typeof RefactorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof UnauthenticatedRouteWithChildren
  '/health': typeof HealthRoute
  '/map-order': typeof MapOrderRoute
  '/matchup': typeof MatchupRoute
  '/pairing': typeof PairingRoute
  '/veto': typeof VetoRoute
  '/api/$': typeof ApiSplatRoute
  '/gameday/$id': typeof UnauthenticatedGamedayIdRoute
  '/refactor': typeof RefactorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_unauthenticated': typeof UnauthenticatedRouteWithChildren
  '/health': typeof HealthRoute
  '/map-order': typeof MapOrderRoute
  '/matchup': typeof MatchupRoute
  '/pairing': typeof PairingRoute
  '/veto': typeof VetoRoute
  '/api/$': typeof ApiSplatRoute
  '/_unauthenticated/gameday/$id': typeof UnauthenticatedGamedayIdRoute
  '/refactor/': typeof RefactorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/health'
    | '/map-order'
    | '/matchup'
    | '/pairing'
    | '/veto'
    | '/api/$'
    | '/gameday/$id'
    | '/refactor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/health'
    | '/map-order'
    | '/matchup'
    | '/pairing'
    | '/veto'
    | '/api/$'
    | '/gameday/$id'
    | '/refactor'
  id:
    | '__root__'
    | '/'
    | '/_unauthenticated'
    | '/health'
    | '/map-order'
    | '/matchup'
    | '/pairing'
    | '/veto'
    | '/api/$'
    | '/_unauthenticated/gameday/$id'
    | '/refactor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UnauthenticatedRoute: typeof UnauthenticatedRouteWithChildren
  HealthRoute: typeof HealthRoute
  MapOrderRoute: typeof MapOrderRoute
  MatchupRoute: typeof MatchupRoute
  PairingRoute: typeof PairingRoute
  VetoRoute: typeof VetoRoute
  ApiSplatRoute: typeof ApiSplatRoute
  RefactorIndexRoute: typeof RefactorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/veto': {
      id: '/veto'
      path: '/veto'
      fullPath: '/veto'
      preLoaderRoute: typeof VetoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pairing': {
      id: '/pairing'
      path: '/pairing'
      fullPath: '/pairing'
      preLoaderRoute: typeof PairingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matchup': {
      id: '/matchup'
      path: '/matchup'
      fullPath: '/matchup'
      preLoaderRoute: typeof MatchupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map-order': {
      id: '/map-order'
      path: '/map-order'
      fullPath: '/map-order'
      preLoaderRoute: typeof MapOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthenticated': {
      id: '/_unauthenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof UnauthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refactor/': {
      id: '/refactor/'
      path: '/refactor'
      fullPath: '/refactor/'
      preLoaderRoute: typeof RefactorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauthenticated/gameday/$id': {
      id: '/_unauthenticated/gameday/$id'
      path: '/gameday/$id'
      fullPath: '/gameday/$id'
      preLoaderRoute: typeof UnauthenticatedGamedayIdRouteImport
      parentRoute: typeof UnauthenticatedRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface UnauthenticatedRouteChildren {
  UnauthenticatedGamedayIdRoute: typeof UnauthenticatedGamedayIdRoute
}

const UnauthenticatedRouteChildren: UnauthenticatedRouteChildren = {
  UnauthenticatedGamedayIdRoute: UnauthenticatedGamedayIdRoute,
}

const UnauthenticatedRouteWithChildren = UnauthenticatedRoute._addFileChildren(
  UnauthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UnauthenticatedRoute: UnauthenticatedRouteWithChildren,
  HealthRoute: HealthRoute,
  MapOrderRoute: MapOrderRoute,
  MatchupRoute: MatchupRoute,
  PairingRoute: PairingRoute,
  VetoRoute: VetoRoute,
  ApiSplatRoute: ApiSplatRoute,
  RefactorIndexRoute: RefactorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
