services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached

    command: sleep infinity

    network_mode: service:db

  db:
    image: surrealdb/surrealdb:latest
    restart: unless-stopped
    command: start --user root --pass root --bind 0.0.0.0:8000 file:/data/onog.db
    volumes:
      - surrealdb-data:/data

    # Add "forwardPorts": ["8000"] to **devcontainer.json** to forward SurrealDB locally.

volumes:
  surrealdb-data:
